# template
[components]
nix = { name = "astros-nix" }
virtio = { name = "astros-virtio" }
input = { name = "astros-input" }
block = { name = "astros-block" }
console = { name = "astros-console" }
softirq = { name = "astros-softirq" }
logger = { name = "astros-logger" }
time = { name = "astros-time" }
framebuffer = { name = "astros-framebuffer" }
network = { name = "astros-network" }
mlsdisk = { name = "astros-mlsdisk" }
nvme = { name = "astros-nvme" }

[whitelist]
[whitelist.nix.main]
main = true
